.\" Manpage for ogg-tagging.
.\" Contact jptrzy@gmail.com to correct errors or typos.
.TH ogg-tagging 1 "26 October 2021" "VERSION" "User Manuals"

.SH NAME
ogg-tagging \- simple ogg music tagger

.SH SYNOPSIS
i3sb [OPTIONS..]

.SH DESCRIPTION
Ogg-tagging is my personal software to tag music in my Music folder.
It takes the name of the music file for music tags.

.SH OPTIONS
.TP
.B \-h
prints this help message
.TP
.BI \-p " path"
set music folder path to 
.I "path" ","
, in default it is set to $HOME/Music
.TP
.B \-d --debug
emit additional debugging messages

.SH FILENAME FORMAT
1 <TITLE>.<EXT>

2 <ARTIST>-<TITLE>.<EXT>

3 <ARTIST>-<ALBUM>-<TITLE>.<EXT>

4 <ARTIST>-<ALBUM>-<TRACK>-<TITLE>.<EXT>

5 <ARTIST>-<ALBUM>-<TRACK>-<TRACKTOTAL>-<TITLE>.<EXT>

.SH SEE ALSO
taglib(1)
.\".SH BUGS
.\"No known bugs.
.SH AUTHOR
jptrzy (jptrzy@gmail.com)
